name: Testing stuff

on:
  schedule:
    - cron: '30 6 * * *'
  push:
    branches:
      - master
      - matt

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://enigmatic-escarpment-69455.herokuapp.com/
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
